### ISSUE TITLE
Accept package directory option to generate files  to

### ISSUE THREAD

**Issue by gernest** [posener/orm#55]
It will be nicer to be able to specify output package where the generated files will live. Most of the time I prefer all generated files to live in a separate package from sources.

example api might be `orm -out ./bar -type Foo` which will created `./bar` if it doesnt exist yet and save generated files for Foo in there, the base path of the -out dir can be used as package name.

**Comment by posener** [comment]
Agree, will be nice to have.
I prepared a ground for that: one of the complication is how to call the type that the ORM was generated for, I added the function `Ext` to type, which get a package name and return `<package>.<Type>` if the package is different and just `<type>` if the package is the same.
I hope I put it in all the right places in the template.

**Comment by gernest** [comment]
I agree, that will pose a challenge indeed.
